# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\x1a\x1cgoogle/protobuf/struct.proto\"\x1f\n\x0c\x42\x61seResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"J\n\x12UpdateFieldRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\" \n\x0fPassportRequest\x12\r\n\x05image\x18\x01 \x01(\t\"\xe1\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x0f\n\x07surname\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\r\n\x05phone\x18\x07 \x01(\t\x12\x0b\n\x03\x61ge\x18\x08 \x01(\r\x12\x17\n\x0ftype_cigarettes\x18\t \x01(\t\x12\r\n\x05score\x18\n \x01(\r\x12\x12\n\nutm_source\x18\x0b \x01(\t\x12\x14\n\x0cquiz_answers\x18\x0c \x01(\t\"-\n\x0cUsersRequest\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\r\n\x05limit\x18\x02 \x01(\r\"1\n\x10\x42lackListRequest\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\r\n\x05limit\x18\x02 \x01(\r\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x04\"(\n\nBanRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\x08\"+\n\x0bQuizRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\xa5\x03\n\x05Users\x12?\n\x0bUpdateField\x12\x19.users.UpdateFieldRequest\x1a\x13.users.BaseResponse\"\x00\x12\x38\n\x08GetUsers\x12\x13.users.UsersRequest\x1a\x13.users.UserResponse\"\x00\x30\x01\x12\x33\n\x0bGetUserById\x12\r.users.UserId\x1a\x13.users.UserResponse\"\x00\x12\x42\n\x0f\x43onfirmPassport\x12\x16.users.PassportRequest\x1a\x13.users.BaseResponse\"\x00\x30\x01\x12:\n\x0cGetBlackList\x12\x17.users.BlackListRequest\x1a\r.users.UserId\"\x00\x30\x01\x12\x33\n\x07\x42\x61nUser\x12\x11.users.BanRequest\x1a\x13.users.BaseResponse\"\x00\x12\x37\n\nQuizAnswer\x12\x12.users.QuizRequest\x1a\x13.users.BaseResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASERESPONSE']._serialized_start=52
  _globals['_BASERESPONSE']._serialized_end=83
  _globals['_UPDATEFIELDREQUEST']._serialized_start=85
  _globals['_UPDATEFIELDREQUEST']._serialized_end=159
  _globals['_PASSPORTREQUEST']._serialized_start=161
  _globals['_PASSPORTREQUEST']._serialized_end=193
  _globals['_USERRESPONSE']._serialized_start=196
  _globals['_USERRESPONSE']._serialized_end=421
  _globals['_USERSREQUEST']._serialized_start=423
  _globals['_USERSREQUEST']._serialized_end=468
  _globals['_BLACKLISTREQUEST']._serialized_start=470
  _globals['_BLACKLISTREQUEST']._serialized_end=519
  _globals['_USERID']._serialized_start=521
  _globals['_USERID']._serialized_end=541
  _globals['_BANREQUEST']._serialized_start=543
  _globals['_BANREQUEST']._serialized_end=583
  _globals['_QUIZREQUEST']._serialized_start=585
  _globals['_QUIZREQUEST']._serialized_end=628
  _globals['_USERS']._serialized_start=631
  _globals['_USERS']._serialized_end=1052
# @@protoc_insertion_point(module_scope)
